// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtVFWGeSIpVt753eW6fWSsHcju2zcLj8I',
    appId: '1:839299513203:web:d6c3436eaf501ec7c7a306',
    messagingSenderId: '839299513203',
    projectId: 'ordertracking-5408f',
    authDomain: 'ordertracking-5408f.firebaseapp.com',
    storageBucket: 'ordertracking-5408f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmWZwEe8DP7MqmY68NJtH-LuGZkYm6MjQ',
    appId: '1:839299513203:android:ed1c49050da92d4cc7a306',
    messagingSenderId: '839299513203',
    projectId: 'ordertracking-5408f',
    storageBucket: 'ordertracking-5408f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBOnKmJEPJg2IaN_0COF_lvt6tCbTuwns',
    appId: '1:839299513203:ios:18d431bd7fbb6dcbc7a306',
    messagingSenderId: '839299513203',
    projectId: 'ordertracking-5408f',
    storageBucket: 'ordertracking-5408f.appspot.com',
    iosClientId: '839299513203-36jufrscljfrql4uifknqrvbn92u17aa.apps.googleusercontent.com',
    iosBundleId: 'com.example.orderApp',
  );
}
